---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: main
    jkube.io/git-url: https://github.com/nithyamani/DO288-apps
    app.openshift.io/vcs-uri: https://github.com/nithyamani/DO288-apps
    jkube.io/git-commit: 5dcc01b9a4babb847a91608666e5277a3cdef92a
    jkube.io/git-branch: main
  labels:
    app: todo-api
    provider: jkube
    version: 1.0.0-SNAPSHOT
    group: com.redhat.training.openshift.todoapi
  name: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
      provider: jkube
      group: com.redhat.training.openshift.todoapi
  template:
    metadata:
      labels:
        app: todo-api
        provider: jkube
        version: 1.0.0-SNAPSHOT
        group: com.redhat.training.openshift.todoapi
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
         - configMapRef: 
             name: configmap-todo-api
        image: todo-api:latest
        imagePullPolicy: IfNotPresent
        name: quarkus
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
